### ISSUE TITLE
Uncaught Error: Class 'SpotTemplateHelper_Bootspot'

### ISSUE THREAD

**Issue by weis999** [Goeny/BootSpot#2]
Hi Goeny,

I am getting the following error,

Fatal error: Uncaught Error: Class 'SpotTemplateHelper_Bootspot' not found in /var/www/spotweb/lib/page/SpotPage_Abs.php:94 Stack trace: #0 /var/www/spotweb/lib/page/SpotPage_Abs.php(40): SpotPage_Abs->getTplHelper(Array) #1 /var/www/spotweb/lib/page/SpotPage_edituserprefs.php(9): SpotPage_Abs->__construct(Object(Dao_Mysql_Factory), Object(Services_Settings_Container), Array) #2 /var/www/spotweb/index.php(242): SpotPage_edituserprefs->__construct(Object(Dao_Mysql_Factory), Object(Services_Settings_Container), Array, Array) #3 {main} thrown in /var/www/spotweb/lib/page/SpotPage_Abs.php on line 94

Do you see a way of solving this problem?

I did a clone on your repository, with the following files inside the map:
![image](https://user-images.githubusercontent.com/31774334/71547324-047c1100-299f-11ea-8765-53b8ee2c2989.png)

This is how I edited the ownsettings.php

![image](https://user-images.githubusercontent.com/31774334/71547330-1c539500-299f-11ea-9e6c-8587cfa0a173.png)

Hope you can help me with this error.

**Comment by Goeny** [comment]
I'm sorry, but i havent worked on this for a long (looooong) time. A lot of changes has been made to Spotweb which i havent tracked for a long time either.

**Comment by Sweepr** [comment]
@weis999

You have to run `composer dump-autoload` which re-generates the autloaders

**Comment by Sweepr** [comment]
I've stumbled upon this today and tried it.

I have managed to get most of it working except for:

![image](https://user-images.githubusercontent.com/2857865/76702580-10888c80-66cb-11ea-90d7-4b53fcbf5ed7.png)

![image](https://user-images.githubusercontent.com/2857865/76702584-1a11f480-66cb-11ea-8c98-119b34fa7db1.png)

![image](https://user-images.githubusercontent.com/2857865/76702591-20a06c00-66cb-11ea-8496-13adffac04c4.png)

![image](https://user-images.githubusercontent.com/2857865/76702594-29913d80-66cb-11ea-8655-cc2feec6329a.png)

Rest is working.

If @Goeny you are willing to assist, maybe we can get it complete and implement this into Spotweb.

**Comment by Sweepr** [comment]
Previews:

![image](https://user-images.githubusercontent.com/2857865/76702669-d79ce780-66cb-11ea-94b4-5e1a0516864d.png)

![image](https://user-images.githubusercontent.com/2857865/76702672-e388a980-66cb-11ea-8214-b16dec2c6c06.png)

**Comment by Goeny** [comment]
@Sweepr 
Thanks for trying to fix some issues.
Unfortunately i really do not have the time to work on it myself. And i havent worked in this for a long time. I'm not sure what changes there have been made by Spotweb. 

Ofcourse you are welcome to implement your fixes yourself.
You can either fork this project or i can check and see if i can add you as dev.

**Comment by Sweepr** [comment]
I am one of the developers of Spotweb, there are a few changes but not that big of a deal.

Only things that need to be finished are the things above.

But.. i'm not sure how it works in Bootstrap theme.

**Comment by Goeny** [comment]
I will set up a testing domain so i can check for some issues myself.
As is said, i hardly have any spare time so it might take some time.

Once those problems are fixed and it's implemented in Spotweb itself, i would love to see someone else take over.

For a good setup... Did you use the latest spotweb? And which version of php did you use?

**Comment by Sweepr** [comment]
I understand, so have i.. ;-)

Thank you!

Best to use the develop branch, and PHP 5.6 or later can be used, better 7.4 which that is the latest supported version.

**Comment by Sweepr** [comment]
If you want i can clone yours, then edit my changes and then push to the repo.

**Comment by Sweepr** [comment]
I have pushed my local changes into Develop branch: https://github.com/Goeny/BootSpot/commit/3f5b33f5d2595608804c4fc2f5660a2cad3a5855

**Comment by Goeny** [comment]
I am running the retreiver now on a clean install with php 7.2 (My server does not support 7.3/7.4 yet)

**Comment by Sweepr** [comment]
I have also updated the Bootstrap version 3.3.1 to the current v4.4.1 in the backup folder is the previous version... not sure if JQuery 1.11.2 is good enough, or if this also needs to be updated.

When we can get these 5 things working then we have a very pretty theme to add ;-)

![image](https://user-images.githubusercontent.com/2857865/76702580-10888c80-66cb-11ea-90d7-4b53fcbf5ed7.png)

![image](https://user-images.githubusercontent.com/2857865/76702584-1a11f480-66cb-11ea-8c98-119b34fa7db1.png)

![image](https://user-images.githubusercontent.com/2857865/76702591-20a06c00-66cb-11ea-8496-13adffac04c4.png)

![image](https://user-images.githubusercontent.com/2857865/76702594-29913d80-66cb-11ea-8655-cc2feec6329a.png)

Would be sad to see such good looking theme go to waste.

**Comment by Goeny** [comment]
> Would be sad to see such good looking theme go to waste.

I know. But as you can see in master branch, it's been about 5-6 years since i last worked on this.
Still using spotweb (as newznab for sonarr/radarr) but haven't looked at (any) code for a looooong time. Will need some time to get back into it.

> I have also updated the Bootstrap version 3.3.1 to the current v4.4.1 in the backup folder is the previous version

I think there have been some changes in the make up between bootstrap v3 and v4. Have to look into that aswell.

Also Font-awesome had updates and make up changes.

This almost seems to become a whole new project.
Let's just take it bit by bit and see how it comes together.. :-)

**Comment by Sweepr** [comment]
> 
> 
> > Would be sad to see such good looking theme go to waste.
> 
> I know. But as you can see in master branch, it's been about 5-6 years since i last worked on this.
> Still using spotweb (as newznab for sonarr/radarr) but haven't looked at (any) code for a looooong time. Will need some time to get back into it.

Luckily Spotweb hasn't changed much over the last years aswell, altough i did make some minor adjustments, i was surprised that much of the stuff was working out of the box so i think you did a pretty nice job there.

**Comment by Sweepr** [comment]
On page ?page=editsettings the switch for `Use different server for headers?` isn't working but i haven't got a clue why.

`Use different server for posting?` just below that is working fine.


![image](https://user-images.githubusercontent.com/2857865/76704566-2fdae600-66da-11ea-8a70-0b84bc752534.png)

**Comment by Goeny** [comment]
![Screenshot_22](https://user-images.githubusercontent.com/3872395/76704758-7b41c400-66db-11ea-9325-b941defefe18.png)

Still running the retreiver.. Will take a look later tonight

**Comment by weis999** [comment]
All right. Will try this next Saturday!

**Comment by Goeny** [comment]
Got it installed again. Unfortunately havent got the time to look into it yet.
Hope to have some news soon.

**Comment by Sweepr** [comment]
@goeny

That's great to hear, take your time, if you have some question feel free to ask.

**Comment by Sweepr** [comment]
@Goeny , I do not want to push you or anything, but i was wondering of you have any news on this theme?

**Comment by STX2k** [comment]
I hope we can see a working theme ;) please keep up the work.
